### PR TITLE
Fix imports in sitemaps.py for Python 2 compatibility

### PR DESCRIPTION
**Pull request by shaib**

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@shaib:

Thank you.

**Comment by shaib** [comment]
@barseghyanartur is a new release expected any time soon? We will soon need a version which supports Django 1.11 on Python 2.7, and we'd rather use a released version.

**Comment by barseghyanartur** [comment]
I'll make a release tonight then.

**Comment by shaib** [comment]
Thanks, that would be great!

**Comment by barseghyanartur** [comment]
@shaib:

Released.

https://pypi.python.org/pypi/django-qartez/0.7.1

**Comment by shaib** [comment]
Thanks a bunch!

**Pull request merged**
